export const lipsumText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod sed ex eget faucibus. Vestibulum at pellentesque nisi, sed feugiat erat. Sed ante ligula, pharetra eu pulvinar tempus, consectetur nec urna. In feugiat, nisl in elementum egestas, urna tortor sagittis ligula, ut efficitur dui nisl sit amet lacus. Morbi a nisl rhoncus, auctor velit non, mollis turpis. Nulla nec pharetra justo, in semper ex. Phasellus sed gravida orci. Maecenas tincidunt neque vitae ante vestibulum venenatis.

Donec sollicitudin suscipit nibh rhoncus placerat. Sed interdum augue ipsum, id mattis sapien efficitur non. Vivamus vulputate, nibh vitae sodales ultrices, lacus mauris mollis leo, eget malesuada tortor tellus vel quam. Nam cursus eget ante eu ullamcorper. In non pulvinar ante, cursus dapibus velit. Maecenas in porta quam. Donec convallis justo id massa pharetra tristique sit amet eu nulla. Sed a massa quis nibh sollicitudin pharetra.

Aenean semper facilisis nibh, ac commodo nunc vestibulum eget. Suspendisse non nunc id arcu consequat ornare. Aliquam erat volutpat. Vestibulum pharetra tortor ac scelerisque auctor. Sed eu nulla et nulla feugiat ultricies. Fusce dignissim tristique leo, sit amet laoreet purus volutpat ut. Sed vel ligula sollicitudin leo vehicula vestibulum. Mauris mollis, sapien eleifend fermentum faucibus, metus ante venenatis lorem, sit amet suscipit leo lorem sed nisl. Mauris nibh ligula, bibendum sit amet vulputate non, elementum sed risus. Nunc tempus suscipit condimentum. Proin condimentum orci eget diam finibus fringilla. Fusce quis blandit nibh.

Sed tempor tellus mauris, non facilisis libero imperdiet et. Suspendisse potenti. Pellentesque at convallis tellus. Praesent eu quam turpis. Mauris id interdum metus, in lacinia libero. Curabitur eget quam semper, interdum tortor ac, imperdiet risus. Sed dignissim, mi at faucibus vestibulum, nunc turpis ultricies risus, et semper metus dolor eu leo. In tempus ante sit amet lectus rhoncus, sit amet efficitur velit gravida. Nullam et diam ac magna tincidunt luctus. In hac habitasse platea dictumst. Donec efficitur id dolor et tempus. Integer laoreet vestibulum risus.

Aliquam in fringilla libero. Curabitur quam nulla, tempor efficitur sollicitudin nec, varius non neque. Aliquam cursus justo at lacus congue, nec sagittis augue porta. Donec laoreet malesuada nunc, eget iaculis arcu dapibus ac. Donec tempor gravida nisi, quis posuere leo efficitur vitae. Phasellus volutpat lorem quam, a ornare purus egestas eu. Phasellus vehicula, lacus id aliquet semper, velit justo commodo velit, sit amet fermentum massa est feugiat quam. Etiam nisi leo, dictum at lectus sed, tincidunt mattis justo. Proin felis justo, maximus vitae faucibus eget, fermentum sed justo. Maecenas et odio quam. Pellentesque elementum posuere commodo. Ut a magna a lorem porttitor ornare non vel nisl. Nam tortor nisi, placerat sagittis ornare quis, posuere ut nunc. Pellentesque eleifend laoreet feugiat. Praesent nec massa ut nibh euismod mollis. Nulla lorem tortor, efficitur id pretium at, faucibus nec leo.`
